### ISSUE TITLE
Warning: glob() expects parameter 2 to be long, string given

### ISSUE THREAD

**Issue by piotrdziubczynski** [johannheyne/wordpress-toolset#2]
Hello.
I have WordPress with ToolSet plugin on my localhost. I'm using docker - the latest version.
After update, in CMS I see two warnings:

1st:
`Warning: glob() expects parameter 2 to be long, string given in /wp-content/plugins/types/vendor/toolset/toolset-common/utility/condition/theme/layouts-support/native/available.php on line 30` 
and 2nd one:
`Warning: Invalid argument supplied for foreach() in /wp-content/plugins/types/vendor/toolset/toolset-common/utility/condition/theme/layouts-support/native/available.php on line 30`

The second warning is due to the first. So... I conducted a small investigation and I've probably found the cause:
> The GLOB_BRACE flag is not available on some non GNU systems.

The solutions for this:
`define('GLOB_BRACE')? GLOB_BRACE : 0;`
or maybe this: http://php.net/manual/pl/function.glob.php#106595

Let me know when this will be fixed.

**Comment by johannheyne** [comment]
Hi Peter,

the warning does not fit to my plugin. There is no file structure /toolset-common/… and no usage of the glob() function. Can you check this please?

Greetings,
Johann

**Comment by piotrdziubczynski** [comment]
I'm sorry. You have right. I typed 'toolset wordpress github' and I came here...
I'm looking different developer.
Sorry once more time.

![screen shot 2017-11-27 at 12 21 20](https://user-images.githubusercontent.com/11270516/33264402-ae12e67e-d36d-11e7-91e4-86e2377762cd.png)
